import './globals.css'
import type { Metadata } from 'next'
import { Inter, Lexend_Deca } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-lexend-deca',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lexendDeca.variable} ${inter.className}`}>{children}</body>
    </html>
  )
}
